/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pembeliantiketkereta.Form;
import pembeliantiketkereta.PersistenceEntity;
import pembeliantiketkereta.controller.*;
/**
 *
 * @author Candi-PC
 */
public class FormLaporan extends javax.swing.JInternalFrame {
    KeretaController Kcont=new KeretaController(PersistenceEntity.emf);
    UserController Ucont=new UserController(PersistenceEntity.emf);
    PenumpangController Pcont=new PenumpangController(PersistenceEntity.emf);
    TransaksiController Tcont=new TransaksiController(PersistenceEntity.emf);
    DetailController Dcont=new DetailController(PersistenceEntity.emf);
    /**
     * Creates new form FormLaporan
     */
    public FormLaporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLapKereta = new javax.swing.JButton();
        btLapUser = new javax.swing.JButton();
        btLapTransaksi = new javax.swing.JButton();
        btLapDetail = new javax.swing.JButton();
        btLapPenum = new javax.swing.JButton();

        btLapKereta.setText("Laporan Kereta");
        btLapKereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLapKeretaActionPerformed(evt);
            }
        });

        btLapUser.setText("Laporan User");
        btLapUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLapUserActionPerformed(evt);
            }
        });

        btLapTransaksi.setText("Laporan Transaksi");
        btLapTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLapTransaksiActionPerformed(evt);
            }
        });

        btLapDetail.setText("Laporan Detail");
        btLapDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLapDetailActionPerformed(evt);
            }
        });

        btLapPenum.setText("Laporan Penumpang");
        btLapPenum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLapPenumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btLapKereta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btLapUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btLapTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(btLapDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btLapPenum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btLapKereta)
                .addGap(18, 18, 18)
                .addComponent(btLapUser)
                .addGap(18, 18, 18)
                .addComponent(btLapTransaksi)
                .addGap(18, 18, 18)
                .addComponent(btLapDetail)
                .addGap(18, 18, 18)
                .addComponent(btLapPenum)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLapKeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLapKeretaActionPerformed
        Kcont.cetak();
    }//GEN-LAST:event_btLapKeretaActionPerformed

    private void btLapUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLapUserActionPerformed
        Ucont.cetak();
    }//GEN-LAST:event_btLapUserActionPerformed

    private void btLapTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLapTransaksiActionPerformed
        Tcont.cetak();
    }//GEN-LAST:event_btLapTransaksiActionPerformed

    private void btLapDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLapDetailActionPerformed
        Dcont.cetak();
    }//GEN-LAST:event_btLapDetailActionPerformed

    private void btLapPenumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLapPenumActionPerformed
        Pcont.cetak();
    }//GEN-LAST:event_btLapPenumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLapDetail;
    private javax.swing.JButton btLapKereta;
    private javax.swing.JButton btLapPenum;
    private javax.swing.JButton btLapTransaksi;
    private javax.swing.JButton btLapUser;
    // End of variables declaration//GEN-END:variables
}
