/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pembeliantiketkereta.Form;
import javax.swing.JOptionPane;
import pembeliantiketkereta.PersistenceEntity;
import pembeliantiketkereta.controller.UserController;
import pembeliantiketkereta.data.User;

/**
 *
 * @author Candi-PC
 */
public class FormUser extends javax.swing.JInternalFrame implements NavigatorFormInterface{
    UserController uscont=new UserController(PersistenceEntity.emf);
    User usr=new User();
    /**
     * Creates new form FormUser
     */
    public FormUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Kode User");

        jLabel2.setText("Nama User");

        jLabel3.setText("Password");

        txtKode.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtNama.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        txtKode.setEnabled(false);
        txtNama.setEnabled(false);
        txtPassword.setEnabled(false);
        bersih();
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables

    @Override
    public void aktif() {
        txtKode.setEnabled(true);
        txtNama.setEnabled(true);
        txtPassword.setEnabled(true);
        txtKode.requestFocus();
    }

    @Override
    public void simpan() {
        usr=uscont.findUser(txtKode.getText());
        User u=new User();
        if(usr==null){
            u.setKodeUser(txtKode.getText());
            u.setNamaUser(txtNama.getText());
            u.setPassword(txtPassword.getText());
            try{
                uscont.save(u);
            }catch(Exception e){}
            JOptionPane.showMessageDialog(null, "Data telah tersimpan");
        }else{
            u.setKodeUser(txtKode.getText());
            u.setNamaUser(txtNama.getText());
            u.setPassword(txtPassword.getText());
            try{
                uscont.update(u);
            }catch(Exception e){}
            JOptionPane.showMessageDialog(null, "Data telah terupdate");           
        }
        bersih();
        txtKode.requestFocus();
    }

    @Override
    public void edit() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void bersih() {
        txtKode.setText("");
        txtNama.setText("");
        txtPassword.setText("");
    }

    @Override
    public void hapus() {
        try{
            uscont.delete(txtKode.getText());
            JOptionPane.showMessageDialog(null, "Data telah dihapus");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Data tidak nisa dihapus karena "+ex.getMessage());
        }
        bersih();
    }

    @Override
    public void cari() {
       usr=uscont.findUser(txtKode.getText());
        if(usr==null){
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
            txtNama.requestFocus();
        }else{
            JOptionPane.showMessageDialog(null, "Data ditemukan");
            tampil();
        }
    }

    @Override
    public void tampil() {
        txtNama.setText(usr.getNamaUser());
        txtPassword.setText(usr.getPassword());
    }
}
